version: '3.8'

services:
  web:
    image: aiastia/youtube-downloader:main
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/static/downloads  # 映射下载目录
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
